name: 02 - Workflow Events

on:
    # deixando assim para evitar que o workflow seja acionado por outros eventos, como push ou schedule
    workflow_dispatch:
    # push:
    # schedule:
    #     - cron: '*/5 * * * *'    # every day at midnight
jobs:
  hello-trigger:  
    runs-on: ubuntu-latest
    steps:
    - name: Show the trigger
      run: | 
        echo "'Hello World'"
        echo "Onde o evento Ã© chamado${{ github.event_name }}"


