name: 03 - workflow-runners

on:
    push:
    workflow_dispatch: {}

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on an Ubuntu runner"
                echo "OS: $(uname -a)"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on a Windows runner"
                systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    
    macos-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on a macOS runner"
                echo "OS: $RUNNER_OS"
